import 'dart:async';

import 'package:flutter/material.dart';

/// 複雜 Widget 樹（150個 SizedBox）
/// 觀察每次build的時間
class Case2Page extends StatefulWidget {
  const Case2Page({super.key});

  @override
  State<Case2Page> createState() => _Case2PageState();
}

class _Case2PageState extends State<Case2Page> {
  @override
  void initState() {
    super.initState();
    Timer.periodic(const Duration(seconds: 3), _update);
  }

  Color _color = Colors.red;
  int _count = 0;

  void _update(Timer timer) {
    if (_count > 10) {
      timer.cancel();
      _count = 0;
      return;
    }
    _count++;
    setState(() {
      _color = _color == Colors.blue ? Colors.red : Colors.blue;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Align(
        child: SizedBox(
            child: SizedBox(
                child: SizedBox(
                    child: SizedBox(
                        child: SizedBox(
                            child: SizedBox(
                                child: SizedBox(
                                    child: SizedBox(
                                        child: SizedBox(
                                            child: SizedBox(
                                                child: SizedBox(
                                                    child: SizedBox(
                                                        child: SizedBox(
                                                            child: SizedBox(
                                                                child: SizedBox(
                                                                    child: SizedBox(
                                                                        child: SizedBox(
                                                                            child: SizedBox(
                                                                                child: SizedBox(
                                                                                    child: SizedBox(
                                                                                        child: SizedBox(
                                                                                            child: SizedBox(
                                                                                                child: SizedBox(
                                                                                                    child: SizedBox(
                                                                                                        child: SizedBox(
                                                                                                            child: SizedBox(
                                                                                                                child: SizedBox(
                                                                                                                    child: SizedBox(
                                                                                                                        child: SizedBox(
                                                                                                                            child: SizedBox(
                                                                                                                                child: SizedBox(
                                                                                                                                    child: SizedBox(
                                                                                                                                        child: SizedBox(
                                                                                                                                            child: SizedBox(
                                                                                                                                                child: SizedBox(
                                                                                                                                                    child: SizedBox(
                                                                                                                                                        child: SizedBox(
                                                                                                                                                            child: SizedBox(
                                                                                                                                                                child: SizedBox(
                                                                                                                                                                    child: SizedBox(
                                                                                                                                                                        child: SizedBox(
                                                                                                                                                                            child: SizedBox(
                                                                                                                                                                                child: SizedBox(
                                                                                                                                                                                    child: SizedBox(
                                                                                                                                                                                        child: SizedBox(
                                                                                                                                                                                            child: SizedBox(
                                                                                                                                                                                                child: SizedBox(
                                                                                                                                                                                                    child: SizedBox(
                                                                                                                                                                                                        child: SizedBox(
                                                                                                                                                                                                            child: SizedBox(
                                                                                                                                                                                                                child: SizedBox(
                                                                                                                                                                                                                    child: SizedBox(
                                                                                                                                                                                                                        child: SizedBox(
                                                                                                                                                                                                                            child: SizedBox(
                                                                                                                                                                                                                                child: SizedBox(
                                                                                                                                                                                                                                    child: SizedBox(
                                                                                                                                                                                                                                        child: SizedBox(
                                                                                                                                                                                                                                            child: SizedBox(
                                                                                                                                                                                                                                                child: SizedBox(
                                                                                                                                                                                                                                                    child: SizedBox(
                                                                                                                                                                                                                                                        child: SizedBox(
                                                                                                                                                                                                                                                            child: SizedBox(
                                                                                                                                                                                                                                                                child: SizedBox(
                                                                                                                                                                                                                                                                    child: SizedBox(
                                                                                                                                                                                                                                                                        child: SizedBox(
                                                                                                                                                                                                                                                                            child: SizedBox(
                                                                                                                                                                                                                                                                                child: SizedBox(
                                                                                                                                                                                                                                                                                    child: SizedBox(
                                                                                                                                                                                                                                                                                        child: SizedBox(
                                                                                                                                                                                                                                                                                            child: SizedBox(
                                                                                                                                                                                                                                                                                                child: SizedBox(
                                                                                                                                                                                                                                                                                                    child: SizedBox(
                                                                                                                                                                                                                                                                                                        child: SizedBox(
                                                                                                                                                                                                                                                                                                            child: SizedBox(
                                                                                                                                                                                                                                                                                                                child: SizedBox(
                                                                                                                                                                                                                                                                                                                    child: SizedBox(
                                                                                                                                                                                                                                                                                                                        child: SizedBox(
                                                                                                                                                                                                                                                                                                                            child: SizedBox(
                                                                                                                                                                                                                                                                                                                                child: SizedBox(
                                                                                                                                                                                                                                                                                                                                    child: SizedBox(
                                                                                                                                                                                                                                                                                                                                        child: SizedBox(
                                                                                                                                                                                                                                                                                                                                            child: SizedBox(
                                                                                                                                                                                                                                                                                                                                                child: SizedBox(
                                                                                                                                                                                                                                                                                                                                                    child: SizedBox(
                                                                                                                                                                                                                                                                                                                                                        child: SizedBox(
                                                                                                                                                                                                                                                                                                                                                            child: SizedBox(
                                                                                                                                                                                                                                                                                                                                                                child: SizedBox(
                                                                                                                                                                                                                                                                                                                                                                    child: SizedBox(
                                                                                                                                                                                                                                                                                                                                                                        child: SizedBox(
                                                                                                                                                                                                                                                                                                                                                                            child: SizedBox(
                                                                                                                                                                                                                                                                                                                                                                                child: SizedBox(
                                                                                                                                                                                                                                                                                                                                                                                    child: SizedBox(
                                                                                                                                                                                                                                                                                                                                                                                        child: SizedBox(
                                                                                                                                                                                                                                                                                                                                                                                            child: SizedBox(
                                                                                                                                                                                                                                                                                                                                                                                                child: SizedBox(
                                                                                                                                                                                                                                                                                                                                                                                                    child: SizedBox(
                                                                                                                                                                                                                                                                                                                                                                                                        child: SizedBox(
                                                                                                                                                                                                                                                                                                                                                                                                            child: SizedBox(
                                                                                                                                                                                                                                                                                                                                                                                                                child: SizedBox(
                                                                                                                                                                                                                                                                                                                                                                                                                    child: SizedBox(
                                                                                                                                                                                                                                                                                                                                                                                                                        child: SizedBox(
                                                                                                                                                                                                                                                                                                                                                                                                                            child: SizedBox(
                                                                                                                                                                                                                                                                                                                                                                                                                                child: SizedBox(
                                                                                                                                                                                                                                                                                                                                                                                                                                    child: SizedBox(
                                                                                                                                                                                                                                                                                                                                                                                                                                        child: SizedBox(
                                                                                                                                                                                                                                                                                                                                                                                                                                            child: SizedBox(
                                                                                                                                                                                                                                                                                                                                                                                                                                                child: SizedBox(
                                                                                                                                                                                                                                                                                                                                                                                                                                                    child: SizedBox(
                                                                                                                                                                                                                                                                                                                                                                                                                                                        child: SizedBox(
                                                                                                                                                                                                                                                                                                                                                                                                                                                            child: SizedBox(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                child: SizedBox(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    child: SizedBox(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        child: SizedBox(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            child: SizedBox(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                child: SizedBox(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    child: SizedBox(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        child: SizedBox(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            child: SizedBox(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                child: SizedBox(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    child: SizedBox(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        child: SizedBox(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            child: SizedBox(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                child: SizedBox(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    child: SizedBox(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        child: SizedBox(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            child: SizedBox(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                child: SizedBox(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    child: SizedBox(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        child: SizedBox(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            child: SizedBox(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                child: SizedBox(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    child: SizedBox(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        child: SizedBox(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            child: SizedBox(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                child: SizedBox(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    child: SizedBox(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        child: SizedBox(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            child: SizedBox(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                child: SizedBox(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    child: SizedBox(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        child: SizedBox(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            child: SizedBox(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                child: SizedBox(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    child: SizedBox(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        child: SizedBox(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            child: SizedBox(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                child: SizedBox(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    child: SizedBox(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        child: SizedBox(
      child: SizedBox(
        width: 100,
        height: 100,
        child: ColoredBox(color: _color),
      ),
    ))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
  }
}
