// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.example.battery_level

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Represents the battery charging state. */
enum class PlatformBatteryState(val raw: Int) {
  CHARGING(0),
  DISCHARGING(1),
  FULL(2),
  UNKNOWN(3);

  companion object {
    fun ofRaw(raw: Int): PlatformBatteryState? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Result containing battery information.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class BatteryInfo (
  /** Battery level as percentage (0-100), or -1 if unknown. */
  val level: Long,
  /** Current battery state. */
  val state: PlatformBatteryState
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BatteryInfo {
      val level = pigeonVar_list[0] as Long
      val state = pigeonVar_list[1] as PlatformBatteryState
      return BatteryInfo(level, state)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      level,
      state,
    )
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PlatformBatteryState.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BatteryInfo.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is PlatformBatteryState -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is BatteryInfo -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/**
 * Host API for battery level operations.
 * Flutter calls these methods to get battery information from native Android.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface BatteryLevelApi {
  /**
   * Returns the current battery level as percentage (0-100).
   * Returns -1 if the battery level cannot be determined.
   */
  fun getBatteryLevel(): Long
  /** Returns the current battery state. */
  fun getBatteryState(): PlatformBatteryState
  /** Returns both battery level and state. */
  fun getBatteryInfo(): BatteryInfo

  companion object {
    /** The codec used by BatteryLevelApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `BatteryLevelApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: BatteryLevelApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.battery_level_android.BatteryLevelApi.getBatteryLevel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getBatteryLevel())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.battery_level_android.BatteryLevelApi.getBatteryState$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getBatteryState())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.battery_level_android.BatteryLevelApi.getBatteryInfo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getBatteryInfo())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
