// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

Future<Uint8List?> combineImagesVertical(
        {required List<Uint8List> imageBytes}) =>
    RustLib.instance.api
        .crateApiSimpleCombineImagesVertical(imageBytes: imageBytes);

Future<Uint8List?> mergeImagesVertically(
        {required List<Uint8List> imageBuffers}) =>
    RustLib.instance.api
        .crateApiSimpleMergeImagesVertically(imageBuffers: imageBuffers);
