from fastapi import HTTPException
from youtube_transcript_api import YouTubeTranscriptApi
from typing import List, Optional
from pydantic import BaseModel, Field


# class AvailableTranslationLanguage(BaseModel):
#     language: Optional[str] = None
#     language_code: Optional[str] = None

class AvailableTranscript(BaseModel):
    video_id: Optional[str] = Field(None, description="The unique identifier for the YouTube video, if available.",
                                    example="bks2zGnssMY")
    language: Optional[str] = Field(None, description="The full name of the language of the transcript.",
                                    example="English")
    language_code: Optional[str] = Field(None, description="The ISO language code for the transcript.", example="en")
    is_generated: Optional[bool] = Field(None, description="Indicates whether the transcript was automatically "
                                                           "generated by YouTube.", example=False)


class AvailableTranscriptResponse(BaseModel):
    video_id: str = Field(..., description="The unique identifier for the YouTube video.", example="bks2zGnssMY")
    available_transcripts: List[AvailableTranscript] = Field(..., description="A list of available transcripts for "
                                                                              "the video, providing details about "
                                                                              "each transcript.")


async def request_available_transcripts(video_id: str):
    try:
        transcripts = YouTubeTranscriptApi.list_transcripts(video_id)
        transcript_details = [
            AvailableTranscript(
                video_id=transcript.video_id,
                language=transcript.language,
                language_code=transcript.language_code,
                is_generated=transcript.is_generated,
                is_translatable=transcript.is_translatable,
                # translation_languages=[
                #     TranslationLanguage(language=lang.get('language'), language_code=lang.get('language_code'))
                #     for lang in transcript.translation_languages
                # ]
            ) for transcript in transcripts
        ]
        return AvailableTranscriptResponse(video_id=video_id, available_transcripts=transcript_details)
    except Exception as e:
        raise HTTPException(status_code=404, detail=str(e))
