name: slidable_bookmarks
description: "A Flutter app demonstrating slidable bookmark functionality."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_slidable: '3.0.1'
  flutter_svg: ^2.0.17
  flutter_riverpod: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  uses-material-design: true
  assets:
    - assets/
