version: '3.8'

services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale-vpn
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=true
    volumes:
      - ./tailscale-data:/var/lib/tailscale
    ports:
      - "1080:1080"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - NET_RAW
    privileged: true
    command: tailscaled -socks5-server=0.0.0.0:1080

networks:
  default:
    driver: bridge
