# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'study_IGListKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for study_IGListKit
  pod 'IGListKit', '~> 4.0.0'
  pod "TinyConstraints"
end
