// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

enum PlatformBatteryState: Int {
  case charging = 0
  case discharging = 1
  case full = 2
  case unknown = 3
}

/// Generated class from Pigeon that represents data sent in messages.
struct BatteryInfo {
  var level: Int64
  var state: PlatformBatteryState


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BatteryInfo? {
    let level = pigeonVar_list[0] as! Int64
    let state = pigeonVar_list[1] as! PlatformBatteryState

    return BatteryInfo(
      level: level,
      state: state
    )
  }
  func toList() -> [Any?] {
    return [
      level,
      state,
    ]
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PlatformBatteryState(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return BatteryInfo.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? PlatformBatteryState {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? BatteryInfo {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol BatteryLevelApi {
  func getBatteryLevel() throws -> Int64
  func getBatteryState() throws -> PlatformBatteryState
  func getBatteryInfo() throws -> BatteryInfo
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class BatteryLevelApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `BatteryLevelApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: BatteryLevelApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let getBatteryLevelChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.battery_level_ios.BatteryLevelApi.getBatteryLevel\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getBatteryLevelChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getBatteryLevel()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getBatteryLevelChannel.setMessageHandler(nil)
    }
    let getBatteryStateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.battery_level_ios.BatteryLevelApi.getBatteryState\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getBatteryStateChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getBatteryState()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getBatteryStateChannel.setMessageHandler(nil)
    }
    let getBatteryInfoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.battery_level_ios.BatteryLevelApi.getBatteryInfo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getBatteryInfoChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getBatteryInfo()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getBatteryInfoChannel.setMessageHandler(nil)
    }
  }
}
